### ISSUE TITLE
very long timeout for connecting to some scitas clusters

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-epfl-supercomputers#2]
For some scitas clusters, ssh takes a very long time to figure out that it cannot connect (bellatrix, castor, deneb1, deneb2), while for others it immediately exits with "no route to host" (eltanin, fidis).

This can be remedied by passing "-o ConnectTimeout=3" to the call to ssh in the `can_login` function, limiting the timeout to 3s.

**Comment by ltalirz** [comment]
This now works via lsmosrv1

**Comment by kjappelbaum** [comment]
I cannot connect to `lsmosrv1` and also have a timeout (deneb)/no route to host (fidis) problem. If it cannot connect without the proxy, I would make this default.
